server:
  port: 8080
spring:
  application:
    name: Delayed-Tasks
  #配置rabbitMq 服务器
  rabbitmq:
    host: ${rabbitmq_host}
    port: ${rabbitmq_port}
    username: ${rabbitmq_username}
    password: ${rabbitmq_password}
    virtual-host: /
  mail:
    default-encoding: utf-8
    host: ${mail_host}
    username: ${mail_username}
    password: ${mail_password}

app:
  params: 1221
